name: Build phar
on:
  push:
    branches: [master]
jobs:
  pharynx:
    name: build phar
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
      - run: composer install --ignore-platform-reqs
      - uses: SOF3/pharynx@v0.2
        id: pharynx
        with:
          additional-assets: |
            icon.png
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: Lottery.phar
          path: ${{steps.pharynx.outputs.output-phar}}
