name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Tests (PHP ${{ matrix.php }})
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ubuntu-latest]
        php: [8.3]

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup PHP
        uses: pmmp/setup-php-action@3c38c259834f945351a662392836d90eb08abff0 # 3.2.0
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: "5"

      - name: Restore Composer package cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ matrix.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --diff --ansi --verbose

      - name: Check spelling
        uses: crate-ci/typos@master
        with: 
          files: ./src ./resources
          write_changes: true

      - name: Run auto commit
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7
        with:
          file_pattern: ./src

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --no-progress --memory-limit=2G
